//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_table()
        {
            this.Stock_table = new HashSet<Stock_table>();
            this.StockIn_Detail_table = new HashSet<StockIn_Detail_table>();
            this.StockOut_Detail_table = new HashSet<StockOut_Detail_table>();
        }
    
        public string BookID { get; set; }
        public string Book_title { get; set; }
        public string CategoryID { get; set; }
        public string Book_Author { get; set; }
        public string PublisherID { get; set; }
        public string Book_Image { get; set; }
        public string Book_BarCode { get; set; }
    
        public virtual Category_table Category_table { get; set; }
        public virtual Publisher_table Publisher_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_table> Stock_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockIn_Detail_table> StockIn_Detail_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOut_Detail_table> StockOut_Detail_table { get; set; }
    }
}
