//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KF31_LliM5_DataBaseEntities : DbContext
    {
        public KF31_LliM5_DataBaseEntities()
            : base("name=KF31_LliM5_DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_table> Book_table { get; set; }
        public virtual DbSet<Category_table> Category_table { get; set; }
        public virtual DbSet<Employee_table> Employee_table { get; set; }
        public virtual DbSet<Libraty_table> Libraty_table { get; set; }
        public virtual DbSet<Possition_table> Possition_table { get; set; }
        public virtual DbSet<Publisher_table> Publisher_table { get; set; }
        public virtual DbSet<Status_table> Status_table { get; set; }
        public virtual DbSet<Stock_table> Stock_table { get; set; }
        public virtual DbSet<StockIn_Detail_table> StockIn_Detail_table { get; set; }
        public virtual DbSet<StockIN_Table> StockIN_Table { get; set; }
        public virtual DbSet<StockOut_Detail_table> StockOut_Detail_table { get; set; }
        public virtual DbSet<StockOut_table> StockOut_table { get; set; }
        public virtual DbSet<User_table> User_table { get; set; }
        public virtual DbSet<Yoyaku_table> Yoyaku_table { get; set; }
        public virtual DbSet<Lend_table> Lend_table { get; set; }
    }
}
