//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lend_table
    {
        public string Lend_ID { get; set; }
        public string YoyakuID { get; set; }
        public Nullable<System.DateTime> Rental_Date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public string Lend_Status { get; set; }
        public string EmployID { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
    
        public virtual Employee_table Employee_table { get; set; }
        public virtual Yoyaku_table Yoyaku_table { get; set; }
    }
}
