//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_table()
        {
            this.Yoyaku_table = new HashSet<Yoyaku_table>();
        }
    
        public string StockID { get; set; }
        public string BookID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string LibratyID { get; set; }
    
        public virtual Book_table Book_table { get; set; }
        public virtual Libraty_table Libraty_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yoyaku_table> Yoyaku_table { get; set; }
    }
}
