//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIN_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockIN_Table()
        {
            this.StockIn_Detail_table = new HashSet<StockIn_Detail_table>();
        }
    
        public string StockIN_ID { get; set; }
        public string statusID { get; set; }
        public Nullable<int> stockIn_Count { get; set; }
        public Nullable<System.DateTime> stockIn_Date { get; set; }
    
        public virtual Status_table Status_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockIn_Detail_table> StockIn_Detail_table { get; set; }
    }
}
