//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIn_Detail_table
    {
        public string StockInDetailID { get; set; }
        public string StockIn_ID { get; set; }
        public string BookID { get; set; }
        public string EmployID { get; set; }
        public Nullable<int> StockIn_Quantity { get; set; }
    
        public virtual Book_table Book_table { get; set; }
        public virtual Employee_table Employee_table { get; set; }
        public virtual StockIN_Table StockIN_Table { get; set; }
    }
}
