//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOut_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockOut_table()
        {
            this.StockOut_Detail_table = new HashSet<StockOut_Detail_table>();
        }
    
        public string StockOut_ID { get; set; }
        public string LibratyID { get; set; }
        public string statusID { get; set; }
        public Nullable<int> stockOut_Count { get; set; }
        public Nullable<System.DateTime> stockOut_Date { get; set; }
    
        public virtual Libraty_table Libraty_table { get; set; }
        public virtual Status_table Status_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOut_Detail_table> StockOut_Detail_table { get; set; }
    }
}
