//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_table()
        {
            this.Yoyaku_table = new HashSet<Yoyaku_table>();
        }
    
        public string userID { get; set; }
        public string DisplayName { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> lasslogin { get; set; }
        public string mail { get; set; }
        public string Tell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yoyaku_table> Yoyaku_table { get; set; }
    }
}
