//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF31_図書館システム版3._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yoyaku_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yoyaku_table()
        {
            this.Lend_table = new HashSet<Lend_table>();
        }
    
        public string YoyakuID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string userID { get; set; }
        public string StockID { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string statusID { get; set; }
        public string Yoyaku_Barcode { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lend_table> Lend_table { get; set; }
        public virtual Status_table Status_table { get; set; }
        public virtual Stock_table Stock_table { get; set; }
        public virtual User_table User_table { get; set; }
    }
}
